/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DIVjXAkZ0I6
 */
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import startrek from "../../imgs/detask9.png"
import "./homepage.css"

// 项目数据数组
const projectsData = [
  {
    id: 1,
    title: "Are You Okay?",
    description: "A Decentralized Check-In Triggered Timed Transfer DApp On Sui Network",
    liveUrl: "https://ruok3.vercel.app/",
    githubUrl: "https://github.com/summertoo/ruok", // 假设的GitHub链接，实际项目中请替换为正确的链接
    icon: "pie-chart"
  },

  {
    id: 0,
    title: "SparkSpace",
    description: "A creative publishing and trading platform that allows app developers, game developers, and teams to list their creative ideas and game resources.",
    liveUrl: "https://sparkspace.wal.app",
    githubUrl: "https://github.com/etboodXJ/DeGameTropicalIsLand", // 假设的GitHub链接，实际项目中请替换为正确的链接
    icon: "briefcase"
  },
  {
    id: 6,
    title: "Mini Soccer",
    description: "Mini Soccer is a game that allows players to play soccer in the metaverse.",
    liveUrl: "https://soccerdemo.edgeone.app/",
    githubUrl: "", // 假设的GitHub链接，实际项目中请替换为正确的链接
    icon: "bar-chart"
  },
  {
    id: 2,
    title: "Hello!Book",
    description: "Hello!Book is a novel website in the form of dAapp, which gathers interactive novels created by combining AI or live action",
    liveUrl: "comingsoon!",
    githubUrl: "", // 假设的GitHub链接，实际项目中请替换为正确的链接
    icon: "smartphone"
  },
  {
    id: 3,
    title: "Sui Write3",
    description: "A platform for novel authors to upload novels",
    liveUrl: "comingsoon!",
    githubUrl: "https://github.com/etboodXJ/SuiWrite3", // 假设的GitHub链接，实际项目中请替换为正确的链接
    icon: "pie-chart"
  },
  {
    id: 4,
    title: "Creator",
    description: "Creator",
    liveUrl: "comingsoon!",
    githubUrl: "", // 假设的GitHub链接，实际项目中请替换为正确的链接
    icon: "pie-chart"
  },
  {
    id: 5,
    title: "Legion Management",
    description: "Game Legion Management",
    liveUrl: "https://www.etboodonline.com/dyj/",
    githubUrl: "", // 假设的GitHub链接，实际项目中请替换为正确的链接
    icon: "pie-chart"
  },

];

// 贡献数据数组
const contributionsData = [
  {
    id: 0,
    title: "Sui Best Practices",
    description: "Contributed to the Sui Best Practices repository with code improvements and documentation",
    projectUrl: "https://github.com/majoson-chen/sui-best-practices",
    contributionUrl: "https://github.com/majoson-chen/sui-best-practices/pull/16",
    icon: "briefcase"
  }
];

export function Homepage() {
  function handleClick(projectId: number): void {
    const project = projectsData.find(p => p.id === projectId);
    if (project) {
      if (project.liveUrl !== "comingsoon!") {
        window.location.href = project.liveUrl;
      } else {
        alert("Coming soon!");
      }
    } else {
      alert("Project not found!");
    }
  }

  function handleGitHubClick(githubUrl: string): void {
    window.open(githubUrl, '_blank');
  }

  function handleContributionClick(contributionUrl: string): void {
    window.open(contributionUrl, '_blank');
  }

  function handleCkContactNow() {
    // window.location.href = 'mailto:etbood@gmail.com';
    // window.open('mailto:etbood@gmail.com');
    alert("etbood@gmail.com")
  }

  function handleCkContactNow2() {
    // window.location.href = 'mailto:etbood@gmail.com';
    window.open('mailto:etbood@gmail.com');
    // alert("mailto:etbood@gmail.com")
  }

  return (
    <div className="max-w-7xl mx-auto px-4">
      <header className="py-6 flex justify-between items-center bg-white text-black">
        <h1 className="text-3xl font-bold">Write ZD Tech </h1>
        <nav>
          <ul className="flex space-x-4">
            <li>
              <a className="text-black hover:text-yellow-700" href="#">
                Home
              </a>
            </li>
            <li>
              <a className="text-black hover:text-yellow-700" href="#">
                What We Do
              </a>
            </li>
            <li>
              <a className="text-black hover:text-yellow-700" href="#">
                Service
              </a>
            </li>
            <li>
              <a className="text-black hover:text-yellow-700" href="#">
                Project
              </a>
            </li>
            <li>
              <a className="text-black hover:text-yellow-700" href="#">
                Blog
              </a>
            </li>
            <li>
              <a className="text-black hover:text-yellow-700" href="#">
                Contact
              </a>
            </li>
          </ul>
        </nav>
      </header>
      <section className="text-center py-20">
        <h2 className="text-4xl font-bold text-black mb-4">
          Integrated portal website
        </h2>
        <p className="mb-6 text-black">
          ZD Technology is a team that provides various aspects of DAPP development, such as web3 applications and games, and provides technical services to a wide range of users
        </p>
        <Button className="bg-black text-white" onClick={() => handleCkContactNow()}>
          Contact Now
        </Button>
      </section>
      {/* <section className="py-20">
        <h3 className="text-3xl font-bold text-center text-black mb-6">Our Client</h3>
        <div className="flex justify-center space-x-8">
          <img
            alt="Google"
            height="24"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/24",
              objectFit: "cover",
            }}
            width="100"
          />
          <img
            alt="Airbnb"
            height="24"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/24",
              objectFit: "cover",
            }}
            width="100"
          />
          <img
            alt="Uber Eats"
            height="24"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/24",
              objectFit: "cover",
            }}
            width="100"
          />
          <img
            alt="Amazon"
            height="24"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/24",
              objectFit: "cover",
            }}
            width="100"
          />
        </div>
      </section> */}
      <section className="py-20">
        <h3 className="text-3xl font-bold text-center text-black mb-6">The following ZD product matrix list will have more products in the future</h3>
        <p className="mb-6 text-black text-center">
          Games&Apps and Others.
        </p>
        <div className="grid grid-cols-2 gap-8">
          {projectsData.map((project) => (
            <Card key={project.id} className="border-black hover:bg-blue-200" >
              <CardContent className="p-5 nowColor" >
                {project.icon === "briefcase" && <BriefcaseIcon className="text-black h-8 w-8" />}
                {project.icon === "bar-chart" && <BarChartIcon className="text-black h-8 w-8" />}
                {project.icon === "smartphone" && <SmartphoneIcon className="text-black h-8 w-8" />}
                {(project.icon === "pie-chart") && <PieChartIcon className="text-black h-8 w-8" />}
                <h4 className="font-semibold text-lg text-black">{project.title}</h4>
                <p>{project.description}</p>
                <div className="flex space-x-2 mt-2">
                  {project.liveUrl !== "comingsoon!" ? (
                    <Button variant="outline" size="sm" onClick={() => handleClick(project.id)} title={project.liveUrl}>
                      Visit
                    </Button>
                  ) : (
                    <Button variant="outline" size="sm" onClick={() => handleClick(project.id)} title={project.liveUrl}>
                      Coming Soon
                    </Button>
                  )}
                  {project.githubUrl && project.githubUrl !== "" && (
                    <Button variant="outline" size="sm" onClick={() => handleGitHubClick(project.githubUrl)} title={project.githubUrl}>
                      GitHub
                    </Button>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>
      <section className="py-20">
        <h3 className="text-3xl font-bold text-center text-black mb-6">Open Source Contributions</h3>
        <p className="mb-6 text-black text-center">
          Contributions to the community.
        </p>
        <div className="grid grid-cols-2 gap-8">
          {contributionsData.map((contribution) => (
            <Card key={contribution.id} className="border-black hover:bg-blue-200" >
              <CardContent className="p-5 nowColor" >
                {contribution.icon === "briefcase" && <BriefcaseIcon className="text-black h-8 w-8" />}
                {contribution.icon === "bar-chart" && <BarChartIcon className="text-black h-8 w-8" />}
                {contribution.icon === "smartphone" && <SmartphoneIcon className="text-black h-8 w-8" />}
                {(contribution.icon === "pie-chart") && <PieChartIcon className="text-black h-8 w-8" />}
                <h4 className="font-semibold text-lg text-black">{contribution.title}</h4>
                <p>{contribution.description}</p>
                <div className="flex space-x-2 mt-2">
                  {contribution.projectUrl && contribution.projectUrl !== "" && (
                    <Button variant="outline" size="sm" onClick={() => window.open(contribution.projectUrl, '_blank')} title={contribution.projectUrl}>
                      Project
                    </Button>
                  )}
                  {contribution.contributionUrl && contribution.contributionUrl !== "" && (
                    <Button variant="outline" size="sm" onClick={() => handleContributionClick(contribution.contributionUrl)} title={contribution.contributionUrl}>
                      My Contributions
                    </Button>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>
      <section className="py-20">
        <h3 className="text-3xl font-bold text-center text-black mb-6">
          2026 is a great interstellar departure
        </h3>
        <div className="flex justify-center">
          <img
            alt="Agency"
            height="300"
            src={startrek}
            style={{
              aspectRatio: "500/300",
              objectFit: "cover",
            }}
            width="500"
          />
        </div>
      </section>
      <section className="py-20 bg-black">
        <h3 className="text-3xl font-bold text-center text-white mb-6">What our happy client say</h3>
        <div className="flex justify-center items-center">
          {/* <Avatar>
            <AvatarImage alt="Matthew Paul" src="/placeholder.svg?height=48&width=48" />
            <AvatarFallback>MP</AvatarFallback>
          </Avatar> */}
          <div className="ml-4">
            <p className="font-semibold text-white">Matthew Paul</p>
            <p className="text-white">
              Perfect, very good job! Thank you for the amazing design and work. Really impressed with the high quality
              and quick turnaround time. Highly recommend.
            </p>
          </div>
        </div>
      </section>
      <section className="py-20">
        <h3 className="text-3xl font-bold text-center text-black mb-6">Subscribe Newsletter</h3>
        <div className="flex justify-center">
          <Input className="mr-4" placeholder="Enter your email address..." type="email" />
          <Button className="bg-black text-white" onClick={() => handleCkContactNow()}>
            Contact Now
          </Button>
        </div>
      </section>
      <footer className="py-10">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
          <div>
            <h5 className="font-bold text-black mb-2">ZD Studio</h5>
            <p className="text-black">
              Leading digital agency with solid design and development expertise. We build readymade websites, mobile
              applications, and elaborate online business services.
            </p>
          </div>
          <div>
            <h5 className="font-bold text-black mb-2">What We Do</h5>
            <ul className="text-black">
              <li>Web Design</li>
              <li>App Design</li>
              <li>Social Media Manage</li>
              <li>Market Analysis Project</li>
            </ul>
          </div>
          <div>
            <h5 className="font-bold text-black mb-2">Company</h5>
            <ul className="text-black">
              <li>About Us</li>
              <li>Career</li>
              <li>Become Investor</li>
            </ul>
          </div>
          <div className="text-black">
            <h5 className="font-bold text-black mb-2">Support</h5>
            <ul>
              <li>FAQ</li>
              <li>Policy</li>
              <li>Business</li>
            </ul>
          </div>
        </div>
        <div className="text-center mt-8">
          <p className="text-black">Copyright © 2026 ZD tech</p>
        </div>
      </footer>
    </div>
  )
}


function BriefcaseIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="7" rx="2" ry="2" />
      <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
    </svg>
  )
}


function BarChartIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>
  )
}


function SmartphoneIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </svg>
  )
}


function PieChartIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      {/* <path d="M21.21 15.89A10 10 0 1 1 8 2.83" />
      <path d="M22 12A10 10 0 0 0 12 2v10z" /> */}
      <path d="M4 18h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2H4c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2z" />
      <path d="M4 18l2-5 2 5h10" />
    </svg>
  )
}