/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DIVjXAkZ0I6
 */
import { Button } from "@/components/ui/button"
import { CardContent, Card } from "@/components/ui/card"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"
import startrek from "../../imgs/detask9.png"
import "./homepage.css"

export function Homepage() {
  function handleClick(param: number): void {
    const urls: any = [
      // "https://detask.walrus.site",
      // "https://lyy.walrus.site",
      // "https://etboodbooks.walrus.site",
      "comingsoon!",
      "comingsoon!",
      "comingsoon!",
      "https://write.wal.app/",
      "comingsoon!",
      "https://www.etboodonline.com/dyj/",

      // 添加更多的 URL 到数组中
    ];

    // 根据参数选择要跳转的 URL
    const selectedUrl = urls[param];

    if (selectedUrl != "comingsoon!") {
      window.location.href = selectedUrl;
    } else {
      // 处理参数无效或无对应 URL 的情况
      alert("coming soon!")
    }
  }

  function handleCkContactNow() {
    // window.location.href = 'mailto:etbood@gmail.com';
    // window.open('mailto:etbood@gmail.com');
    alert("etbood@gmail.com")
  }

  function handleCkContactNow2() {
    // window.location.href = 'mailto:etbood@gmail.com';
    window.open('mailto:etbood@gmail.com');
    // alert("mailto:etbood@gmail.com")
  }

  return (
    <div className="max-w-7xl mx-auto px-4">
      <header className="py-6 flex justify-between items-center bg-white text-black">
        <h1 className="text-3xl font-bold">Write ZD Tech </h1>
        <nav>
          <ul className="flex space-x-4">
            <li>
              <a className="text-black hover:text-yellow-700" href="#">
                Home
              </a>
            </li>
            <li>
              <a className="text-black hover:text-yellow-700" href="#">
                What We Do
              </a>
            </li>
            <li>
              <a className="text-black hover:text-yellow-700" href="#">
                Service
              </a>
            </li>
            <li>
              <a className="text-black hover:text-yellow-700" href="#">
                Project
              </a>
            </li>
            <li>
              <a className="text-black hover:text-yellow-700" href="#">
                Blog
              </a>
            </li>
            <li>
              <a className="text-black hover:text-yellow-700" href="#">
                Contact
              </a>
            </li>
          </ul>
        </nav>
      </header>
      <section className="text-center py-20">
        <h2 className="text-4xl font-bold text-black mb-4">
          Integrated portal website
        </h2>
        <p className="mb-6 text-black">
          ZD Technology is a team that provides various aspects of DAPP development, such as web3 applications and games, and provides technical services to a wide range of users
        </p>
        <Button className="bg-black text-white" onClick={() => handleCkContactNow()}>
          Contact Now
        </Button>
      </section>
      {/* <section className="py-20">
        <h3 className="text-3xl font-bold text-center text-black mb-6">Our Client</h3>
        <div className="flex justify-center space-x-8">
          <img
            alt="Google"
            height="24"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/24",
              objectFit: "cover",
            }}
            width="100"
          />
          <img
            alt="Airbnb"
            height="24"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/24",
              objectFit: "cover",
            }}
            width="100"
          />
          <img
            alt="Uber Eats"
            height="24"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/24",
              objectFit: "cover",
            }}
            width="100"
          />
          <img
            alt="Amazon"
            height="24"
            src="/placeholder.svg"
            style={{
              aspectRatio: "100/24",
              objectFit: "cover",
            }}
            width="100"
          />
        </div>
      </section> */}
      <section className="py-20">
        <h3 className="text-3xl font-bold text-center text-black mb-6">The following ZD product matrix list will have more products in the future</h3>
        <p className="mb-6 text-black text-center">
          Games&Apps and Others.
        </p>
        <div className="grid grid-cols-2 gap-8">
          <Card className="border-black hover:bg-blue-200" >
            <CardContent className="p-5 nowColor" onClick={() => handleClick(5)}>
              <PieChartIcon className="text-black h-8 w-8" />
              <h4 className="font-semibold text-lg text-black">Legion Management</h4>
              <p>Game Legion Management</p>
            </CardContent>
          </Card>
          <Card className="border-black hover:bg-blue-200">
            <CardContent className="p-5 nowColor" onClick={() => handleClick(0)}>
              <BriefcaseIcon className="text-black h-8 w-8" />
              <h4 className="font-semibold text-lg text-black">DeTask</h4>
              <p>DeTask is a decentralized job search and communication platform</p>
            </CardContent>
          </Card>
          <Card className="border-black hover:bg-blue-200">
            <CardContent className="p-5 nowColor" onClick={() => handleClick(1)}>
              <BarChartIcon className="text-black h-8 w-8" />
              <h4 className="font-semibold text-lg text-black">Paradise</h4>
              <p>Paradise is a dAapp game center that includes various forms of dApp games</p>
            </CardContent>
          </Card>
          <Card className="border-black hover:bg-blue-200" >
            <CardContent className="p-5 nowColor" onClick={() => handleClick(2)}>
              <SmartphoneIcon className="text-black h-8 w-8" />
              <h4 className="font-semibold text-lg text-black">Hello!Book</h4>
              <p>Hello!Book is a novel website in the form of dAapp, which gathers interactive novels created by combining AI or live action</p>
            </CardContent>
          </Card>
          <Card className="border-black hover:bg-blue-200" >
            <CardContent className="p-5 nowColor" onClick={() => handleClick(3)}>
              <PieChartIcon className="text-black h-8 w-8" />
              <h4 className="font-semibold text-lg text-black">Sui Write3</h4>
              <p>A platform for novel authors to upload novels</p>
            </CardContent>
          </Card>
          <Card className="border-black hover:bg-blue-200" >
            <CardContent className="p-5 nowColor" onClick={() => handleClick(4)}>
              <PieChartIcon className="text-black h-8 w-8" />
              <h4 className="font-semibold text-lg text-black">Creator</h4>
              <p>Creator</p>
            </CardContent>
          </Card>

        </div>
      </section>
      <section className="py-20">
        <h3 className="text-3xl font-bold text-center text-black mb-6">
          2025 is a great interstellar departure
        </h3>
        <div className="flex justify-center">
          <img
            alt="Agency"
            height="300"
            src={startrek}
            style={{
              aspectRatio: "500/300",
              objectFit: "cover",
            }}
            width="500"
          />
        </div>
      </section>
      <section className="py-20 bg-black">
        <h3 className="text-3xl font-bold text-center text-white mb-6">What our happy client say</h3>
        <div className="flex justify-center items-center">
          {/* <Avatar>
            <AvatarImage alt="Matthew Paul" src="/placeholder.svg?height=48&width=48" />
            <AvatarFallback>MP</AvatarFallback>
          </Avatar> */}
          <div className="ml-4">
            <p className="font-semibold text-white">Matthew Paul</p>
            <p className="text-white">
              Perfect, very good job! Thank you for the amazing design and work. Really impressed with the high quality
              and quick turnaround time. Highly recommend.
            </p>
          </div>
        </div>
      </section>
      <section className="py-20">
        <h3 className="text-3xl font-bold text-center text-black mb-6">Subscribe Newsletter</h3>
        <div className="flex justify-center">
          <Input className="mr-4" placeholder="Enter your email address..." type="email" />
          <Button className="bg-black text-white" onClick={() => handleCkContactNow()}>
            Contact Now
          </Button>
        </div>
      </section>
      <footer className="py-10">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
          <div>
            <h5 className="font-bold text-black mb-2">ZD Studio</h5>
            <p className="text-black">
              Leading digital agency with solid design and development expertise. We build readymade websites, mobile
              applications, and elaborate online business services.
            </p>
          </div>
          <div>
            <h5 className="font-bold text-black mb-2">What We Do</h5>
            <ul className="text-black">
              <li>Web Design</li>
              <li>App Design</li>
              <li>Social Media Manage</li>
              <li>Market Analysis Project</li>
            </ul>
          </div>
          <div>
            <h5 className="font-bold text-black mb-2">Company</h5>
            <ul className="text-black">
              <li>About Us</li>
              <li>Career</li>
              <li>Become Investor</li>
            </ul>
          </div>
          <div className="text-black">
            <h5 className="font-bold text-black mb-2">Support</h5>
            <ul>
              <li>FAQ</li>
              <li>Policy</li>
              <li>Business</li>
            </ul>
          </div>
        </div>
        <div className="text-center mt-8">
          <p className="text-black">Copyright © 2025 ZD tech</p>
        </div>
      </footer>
    </div>
  )
}


function BriefcaseIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="14" x="2" y="7" rx="2" ry="2" />
      <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
    </svg>
  )
}


function BarChartIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="20" y2="10" />
      <line x1="18" x2="18" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="16" />
    </svg>
  )
}


function SmartphoneIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </svg>
  )
}


function PieChartIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      {/* <path d="M21.21 15.89A10 10 0 1 1 8 2.83" />
      <path d="M22 12A10 10 0 0 0 12 2v10z" /> */}
      <path d="M4 18h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2H4c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2z" />
      <path d="M4 18l2-5 2 5h10" />
    </svg>
  )
}
